### ISSUE TITLE
Issue when running "habillage=" argument.

### ISSUE THREAD

**Issue by orbisvitae** [kassambara/factoextra#3]
Returns: "Error: Unknown parameters: pointsize"

This is even true using the "tea" dataset plot example/s given in the guide posted. Otherwise everything seems to work fine and charts are well generated. 

Example:
>data(tea)
>res.mca <- MCA(tea, quanti.sup=19, quali.sup=20:36)
>fviz_mca_ind(res.mca, label='none', habillage=tea$sex, addEllipses = TRUE, ellipse.level = 0.95 )
>Error: Unknown parameters: pointsize

**Comment by kassambara** [comment]
The bug has been fixed know... 

Please, install the latest version of factoextra and let me know if it works for you.

Thank you for your contribution,
AK

**Comment by REMYGDS** [comment]
Hi
I have exactey the same problem
R version 3.2.4 Windows

> res.mca <- MCA(dMCA, graph=FALSE)
> grp <- as.factor(dMCA[, "VAR3"])
> fviz_mca_ind(res.mca, label="none", habillage=grp)
Error: Unknown parameters: pointsize

RV

**Comment by kassambara** [comment]
Hi,

Could you please provide your  R session info.

If you have the latest version of factoextra, it should work:

```r
# Install factoextra
devtools::install_github("kassambara/factoextra")
# Use factoextra
library("FactoMineR")
library("factoextra")

data(tea)
res.mca <- MCA(tea, quanti.sup=19, quali.sup=20:36)
# Normal pointsize
fviz_mca_ind(res.mca, label='none', habillage=tea$sex, 
         addEllipses = TRUE, ellipse.level = 0.95 )
```

![rplot](https://cloud.githubusercontent.com/assets/3313355/14284154/981ff9ca-fb46-11e5-887e-056fda5f4ac9.png)

```r
# pointsize = 10
fviz_mca_ind(res.mca, label='none', habillage=tea$sex, 
         addEllipses = TRUE, ellipse.level = 0.95 ,
         pointsize = 10)
```
 
![rplot08](https://cloud.githubusercontent.com/assets/3313355/14284196/bd63c28e-fb46-11e5-863a-8b8225902d66.png)

My session info: 
<pre>
Session info -----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2016-04-05                  

Packages ---------------------------------------------------------------------------------------------------------------------
 package       * version    date       source                                
 car             2.1-1      2015-12-14 CRAN (R 3.2.3)                        
 cluster         2.0.3      2015-07-21 CRAN (R 3.2.3)                        
 colorspace      1.2-6      2015-03-11 CRAN (R 3.2.0)                        
 curl            0.9.5      2016-01-23 CRAN (R 3.2.3)                        
 devtools      * 1.10.0     2016-01-23 CRAN (R 3.2.3)                        
 digest          0.6.9      2016-01-08 CRAN (R 3.2.3)                        
 factoextra    * 1.0.3.9000 2016-04-05 Github (kassambara/factoextra@34cb116)
 FactoMineR    * 1.31.4     2015-10-10 CRAN (R 3.2.0)                        
 flashClust      1.01-2     2012-08-21 CRAN (R 3.2.0)                        
 ggplot2       * 2.1.0      2016-03-01 CRAN (R 3.2.4)                        
 ggrepel         0.5        2016-02-08 CRAN (R 3.2.3)                        
 git2r           0.13.1     2015-12-10 CRAN (R 3.2.3)                        
 gtable          0.2.0      2016-02-26 CRAN (R 3.2.3)                        
 httr            1.1.0      2016-01-28 CRAN (R 3.2.3)                        
 labeling        0.3        2014-08-23 CRAN (R 3.2.0)                        
 lattice         0.20-33    2015-07-14 CRAN (R 3.2.3)                        
 leaps           2.9        2009-05-05 CRAN (R 3.2.0)                        
 lme4            1.1-10     2015-10-06 CRAN (R 3.2.2)                        
 MASS            7.3-45     2015-11-10 CRAN (R 3.2.3)                        
 Matrix          1.2-3      2015-11-28 CRAN (R 3.2.3)                        
 MatrixModels    0.4-1      2015-08-22 CRAN (R 3.2.0)                        
 memoise         1.0.0      2016-01-29 CRAN (R 3.2.3)                        
 mgcv            1.8-10     2015-12-12 CRAN (R 3.2.3)                        
 minqa           1.2.4      2014-10-09 CRAN (R 3.2.0)                        
 munsell         0.4.3      2016-02-13 CRAN (R 3.2.3)                        
 nlme            3.1-122    2015-08-19 CRAN (R 3.2.3)                        
 nloptr          1.0.4      2014-08-04 CRAN (R 3.2.0)                        
 nnet            7.3-11     2015-08-30 CRAN (R 3.2.3)                        
 pbkrtest        0.4-4      2015-12-12 CRAN (R 3.2.1)                        
 plyr            1.8.3      2015-06-12 CRAN (R 3.2.0)                        
 quantreg        5.19       2015-08-31 CRAN (R 3.2.0)                        
 R6              2.1.2      2016-01-26 CRAN (R 3.2.3)                        
 Rcpp            0.12.4     2016-03-26 CRAN (R 3.2.4)                        
 scales          0.4.0      2016-02-26 CRAN (R 3.2.3)                        
 scatterplot3d   0.3-36     2015-07-30 CRAN (R 3.2.0)                        
 SparseM         1.7        2015-08-15 CRAN (R 3.2.0)                        
 withr           1.0.1      2016-02-04 CRAN (R 3.2.3) 
</pre>

Best,
AK

**Comment by REMYGDS** [comment]
Hi,

I’ve found solution
It was because of a bad installation of R

Thanks a lot for informations

Best

REMY
[cid:image003.png@01D18F57.346165A0]

www.gds-bretagne.fr <http://www.gds-bretagne.fr/>


Rémy VERMESSE
vétérinaire

Rue Maurice le Lannou,
CS74241 35042 Rennes Cedex
Tél  02 23 48 26 00 / Port 06 19 14 84 97






De : Alboukadel KASSAMBARA [mailto:notifications@github.com]
Envoyé : mardi 5 avril 2016 15:56
À : kassambara/factoextra
Cc : VERMESSE Rémy
Objet : Re: [kassambara/factoextra] Issue when running "habillage=" argument. (#3)


Hi,

Could you please provide your R session info.

If you have the latest version of factoextra, it should work:

# Install factoextra

devtools::install_github("kassambara/factoextra")

# Use factoextra

library("FactoMineR")

library("factoextra")



data(tea)

res.mca <- MCA(tea, quanti.sup=19, quali.sup=20:36)

# Normal pointsize

fviz_mca_ind(res.mca, label='none', habillage=tea$sex,

         addEllipses = TRUE, ellipse.level = 0.95 )

[Image supprimée par l'expéditeur. rplot]<https://cloud.githubusercontent.com/assets/3313355/14284154/981ff9ca-fb46-11e5-887e-056fda5f4ac9.png>

# pointsize = 10

fviz_mca_ind(res.mca, label='none', habillage=tea$sex,

         addEllipses = TRUE, ellipse.level = 0.95 ,

         pointsize = 10)

[Image supprimée par l'expéditeur. rplot08]<https://cloud.githubusercontent.com/assets/3313355/14284196/bd63c28e-fb46-11e5-863a-8b8225902d66.png>

My session info:

Session info -----------------------------------------------------------------------------------------------------------------

 setting  value

 version  R version 3.2.3 (2015-12-10)

 system   x86_64, darwin13.4.0

 ui       RStudio (0.99.491)

 language (EN)

 collate  fr_FR.UTF-8

 tz       Europe/Paris

 date     2016-04-05



Packages ---------------------------------------------------------------------------------------------------------------------

 package       * version    date       source

 car             2.1-1      2015-12-14 CRAN (R 3.2.3)

 cluster         2.0.3      2015-07-21 CRAN (R 3.2.3)

 colorspace      1.2-6      2015-03-11 CRAN (R 3.2.0)

 curl            0.9.5      2016-01-23 CRAN (R 3.2.3)

 devtools      * 1.10.0     2016-01-23 CRAN (R 3.2.3)

 digest          0.6.9      2016-01-08 CRAN (R 3.2.3)

 factoextra    * 1.0.3.9000 2016-04-05 Github (kassambara/factoextra@34cb116)

 FactoMineR    * 1.31.4     2015-10-10 CRAN (R 3.2.0)

 flashClust      1.01-2     2012-08-21 CRAN (R 3.2.0)

 ggplot2       * 2.1.0      2016-03-01 CRAN (R 3.2.4)

 ggrepel         0.5        2016-02-08 CRAN (R 3.2.3)

 git2r           0.13.1     2015-12-10 CRAN (R 3.2.3)

 gtable          0.2.0      2016-02-26 CRAN (R 3.2.3)

 httr            1.1.0      2016-01-28 CRAN (R 3.2.3)

 labeling        0.3        2014-08-23 CRAN (R 3.2.0)

 lattice         0.20-33    2015-07-14 CRAN (R 3.2.3)

 leaps           2.9        2009-05-05 CRAN (R 3.2.0)

 lme4            1.1-10     2015-10-06 CRAN (R 3.2.2)

 MASS            7.3-45     2015-11-10 CRAN (R 3.2.3)

 Matrix          1.2-3      2015-11-28 CRAN (R 3.2.3)

 MatrixModels    0.4-1      2015-08-22 CRAN (R 3.2.0)

 memoise         1.0.0      2016-01-29 CRAN (R 3.2.3)

 mgcv            1.8-10     2015-12-12 CRAN (R 3.2.3)

 minqa           1.2.4      2014-10-09 CRAN (R 3.2.0)

 munsell         0.4.3      2016-02-13 CRAN (R 3.2.3)

 nlme            3.1-122    2015-08-19 CRAN (R 3.2.3)

 nloptr          1.0.4      2014-08-04 CRAN (R 3.2.0)

 nnet            7.3-11     2015-08-30 CRAN (R 3.2.3)

 pbkrtest        0.4-4      2015-12-12 CRAN (R 3.2.1)

 plyr            1.8.3      2015-06-12 CRAN (R 3.2.0)

 quantreg        5.19       2015-08-31 CRAN (R 3.2.0)

 R6              2.1.2      2016-01-26 CRAN (R 3.2.3)

 Rcpp            0.12.4     2016-03-26 CRAN (R 3.2.4)

 scales          0.4.0      2016-02-26 CRAN (R 3.2.3)

 scatterplot3d   0.3-36     2015-07-30 CRAN (R 3.2.0)

 SparseM         1.7        2015-08-15 CRAN (R 3.2.0)

 withr           1.0.1      2016-02-04 CRAN (R 3.2.3)

Best,
AK

**Comment by kassambara** [comment]
You're welcome!

Best,
AK
